### ISSUE TITLE
Special characters in URL encoded twice

### ISSUE THREAD

**Issue by limzykenneth** [mhart/aws4fetch#31] opened 2021-04-03 16:54 UTC
I'm using aws4fetch with cloudflare workers to fetch files from an S3 storage but the file in question has a special character in it (eg. `é`) and it doesn't work. On closer inspection I found out that the character has been encoded twice: `é -> %C3%A8 -> %25C3%25A8` when it should have been encoded once only.

Passing `singleEncode` option to fetch resolves this problem but looking at the description of it in README seems to indicate that this wasn't designed for this use case but rather for some unspecified test case, so I can't be sure if using `singleEncode` will cause other problems or not.

**Comment by mhart** [comment] 2021-04-03 16:58
Can you post some code of how you're using it? There are tests that specifically cover this use case that work just fine on live AWS services:

https://github.com/mhart/aws4fetch/blob/447d747ab99bd7cb58afbe1da9b1af88c787cae7/test/integration.js#L55

**Comment by limzykenneth** [comment] 2021-04-03 19:17
Adapted from example from Cloudflare Workers:
```javascript
async function handleRequest(request) {
  const {method, body} = request;
  const url = new URL(request.url);
  url.hostname = bucket + hostname;
  
  const data = await aws
    .fetch(url, {
      method,
      body
    )
    .then(res => res.arrayBuffer());

  return new Response(data, {
    headers: {
      "Content-Type": "video/mp4",
    },
  });
```

I'm using Backblaze's S3 endpoint, haven't tried it with AWS itself.

**Comment by mhart** [comment] 2021-04-03 19:55
Ah, you said "S3 storage". I have no idea about Backblaze, maybe they don't encode in the same way S3 does.

Going to close this as it's working as intended with S3.

**Closed by mhart** 2021-04-03 19:55 UTC

**Comment by limzykenneth** [comment] 2021-04-03 21:05
I just found that the URL encoding for accented characters for AWS and Backblaze is different. For Backblaze, `è` is encoded as `%C3%A8` which is the same as `encodeURI` while AWS encodes it as `e%CC%80` which is pretty weird for URLs.

I still don't get why in Backblaze's case it would get encoded twice while suddenly not in the case of AWS though.

**Comment by mhart** [comment] 2021-04-04 01:08
> Also passing a URL with `è` in it will not work in AWS's case as browsers will encode them as `%C3%A8` instead of `e%CC%80`.

Can you show me some code that doesn't work with AWS?

**Comment by limzykenneth** [comment] 2021-04-04 20:14
It literally is the example code for Cloudflare worker [here](https://github.com/conzorkingkong/cloud-storage), no need to modify beyond changing the bucket and endpoint URL (if needed) and setting the keys env. The file requested has the `è` in the filename, the rest don't matter (I have many other file that works without problems).

Once the worker is running through `wrangler dev`, visit `http://localhost:8787/[path to file with è in it]` in a browser.

If you manually replace `è` with `e%CC%80` in the URL bar it will work but copy and pasting or typing it into the URL bar will return the following error

```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>[file name]</Key>
  <RequestId>...</RequestId>
  <HostId>
    ...
  </HostId>
</Error>
```

**Comment by mhart** [comment] 2021-04-04 21:50
Sorry, that doesn't seem to be an AWS endpoint? You're talking with localhost

**Comment by mhart** [comment] 2021-04-04 21:59
Ah, I see – it's a proxy through to S3 right? The thing is, the signature is correct in both cases, otherwise you'd get a signing error. What's the file that you've uploaded to S3?

**Comment by limzykenneth** [comment] 2021-04-04 23:07
It's a video file but I'd imagine it should be the same case with any other files since it's a URL encoding problem.

**Comment by mhart** [comment] 2021-04-04 23:39
Sorry, I meant what's the file's actual name in the S3 bucket? Can you give a screenshot of how it looks in the S3 console?

**Comment by limzykenneth** [comment] 2021-04-05 16:16
Any file with a è character in the file name will do. For my test I created a dummy text file with name `pièce.txt`.

<img width="1232" alt="Screenshot 2021-04-05 at 5 14 36 pm" src="https://user-images.githubusercontent.com/7543950/113596674-90fd9080-9632-11eb-9ef6-e7827dac7d4a.png">

**Comment by mhart** [comment] 2022-10-09 18:35
Hi @limzykenneth – I'm just revisiting this after a long time just to make sure nothing was broken.

I'm not sure what's going on in your case, but both of these work just fine for me (with or without encoding):
```js
return new AwsClient({
  accessKeyId: env.AWS_ACCESS_KEY_ID,
  secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
}).fetch(new Request("https://jwpricing.s3.amazonaws.com/pi%C3%A8ce.txt"));
```

```js
return new AwsClient({
  accessKeyId: env.AWS_ACCESS_KEY_ID,
  secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
}).fetch(new Request("https://jwpricing.s3.amazonaws.com/pièce.txt"));
```

**Comment by limzykenneth** [comment] 2022-10-10 09:06
I've since used some workaround to avoid special characters and I'm no longer using aws4fetch as the official SDK works on a variety of JS runtime including Cloudflare Workers so I'm using that instead.
