### ISSUE TITLE
Creating presigned urls

### ISSUE THREAD

**Issue by febg11** [mhart/aws4fetch#32] opened 2021-04-10 14:01 UTC
Hi 

I am trying to create presigned urls for objects on digital ocean using your library. I cannot use the default aws package as i need the X-Amz-Date. to be in the future. 

I have tried to just generate a url (which i get) but I always get permission denied. The urls are currently being generated in the browser.

Here is what I have tried 

```
this.awsClient = new AwsClient({ accessKeyId: environment.ACCESS_KEY_ID, secretAccessKey: environment.SECRET_ACCESS_KEY });


const result = await this.awsClient.sign('https://[BUCKET_NAME].[REGION].digitaloceanspaces.com/[PATH]', {
    method: 'GET',
    aws: {
      signQuery: true,
    },
  },
)

```

result.url has a similar url to those generated using the aws sdk.

Futhermore, are we able to add expire params during the signing process. I guess they would go in the headers or body but wasnt sure. 

Thanks a lot

**Comment by mhart** [comment] 2021-04-10 20:23
I'm not sure about Digital Ocean I'm afraid, but other ppl have had success with it. You'll just need to force the service to be `s3`. Closing as a dupe of https://github.com/mhart/aws4fetch/issues/15#issuecomment-628237321

**Closed by mhart** 2021-04-10 20:23 UTC

**Comment by febg11** [comment] 2021-04-10 20:32
i saw that issue earlier and had no luck with it

**Comment by febg11** [comment] 2021-04-11 10:04
Hi again.

I have done some digging and have come up with a few questions. 

I have tried generating a presigned url using your node library aws4 and it works fine. My code looks like this:
```
const options = {
  host: ‘<BUCKET_NAME>.<REGION>.digitaloceanspaces.com',
  region: <‘REGION>,
  service: 's3',
  path: “/pathToFile”,
  signQuery: true,
}


const url = aws4.sign(options, {
  secretAccessKey: “<SECRET>”,
  accessKeyId: “<ACCESS”_KEY>,
});

```

Now when I do the same thing in the aws4Fetch library I get signature does not match for everything I do.. here is my code
```
  const newMethod = await this.awsClient.sign('https://<BUCKEt>.<REGION>.digitaloceanspaces.com/<PATH_TO_FILE>', {
      method: 'GET',
      headers: {},
      aws: {
        signQuery: true,
      },
    },
  )
```


Now something I noticed that was different between the URLS generated by aws4 and aws4Fetch was the X-Amz-SignedHeaders were different.

Node aws4: ```X-Amz-SignedHeaders=host```

Browser asw4Fetch: ```X-Amz-SignedHeaders=host%3Bx-amz-content-sha256```
 

I have tried to remove this part of the aws4Fetch library 

```
    if (this.service === 's3' && !this.headers.has('X-Amz-Content-Sha256')) {
        this.headers.set('X-Amz-Content-Sha256', 'UNSIGNED-PAYLOAD');
      }
```

And it fixes the signature does not match error? Could you explain what this is used for.and why it appends the X-Amz-Content-Sha256.


Possible related note: 
I found someone experiencing a similar issue in the php library on stackoverflow ->
 https://stackoverflow.com/questions/51943709/aws-s3-bucket-presigned-url
https://github.com/aws/aws-sdk-php/issues/1609 

Kind Regards

**Comment by tricepat** [comment] 2021-06-04 13:13
Hi @febg11 , running into the same issue–how did you resolve this in the end?

**Comment by febg11** [comment] 2021-06-04 21:02
Didn't use this library. Ended up using the aws4 node version and making an server that returns them

**Comment by CanRau** [comment] 2024-12-21 14:17
This works for me

```ts
const client = new AwsClient({
  accessKeyId: env.DO_SPACES_ACCESS_KEY_ID,
  secretAccessKey: env.DO_SPACES_SECRET_ACCESS_KEY,
  region: "fra1",
});

const signedRequest = await client.client.sign(`https://${bucket}.${region}.digitaloceanspaces.com/${filePath}`, {
  method: "GET",
  aws: { signQuery: true, service: "s3" },
});
```
